import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.scss';
import LayoutClient from './layout.client';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: "Spotify - Web Player: Music for everyone",
	description: 'Generated by Mar4ik Dev'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<LayoutClient>{children}</LayoutClient>
			</body>
		</html>
	);
}
